### ISSUE TITLE
performance on CIFAR100

### ISSUE THREAD

**Issue by dongfangduoshou123** [leaderj1001/MobileNetV3-Pytorch#7]
Hi, 
Use your code on CIFAR100, only after 34 epoch, I got acc1:70.43, acc5:91.08 on CIFAR100_test_data with batch_size=64.
You use 80 epoch with batch_size=512 just got acc1:70.44 acc5:91.34?

Note:model_mode = 'LARGE'

**Comment by leaderj1001** [comment]
Thank you for your issue :)
Currently the default hyper-parameters are the default values for the imagenet dataset.
Thank you !
